name: Build dependencies for ggsugar package

on:
  push:
    branches:
      - master

jobs:
  build-webpack:
    uses: ./.github/workflows/webpack_build.yml
  build-sugars:
    needs: build-webpack
    uses: ./.github/workflows/package_build.yml
