name: Build package contents

on: push

jobs:
  build-sugars:
    container: rocker/tidyverse:4
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install apt packages
        run: |
          apt-get update && apt-get install --no-install-recommends -y libjpeg-dev libcairo2-dev libspectre-dev librsvg2-dev libpoppler-glib-dev libv8-dev && rm -rf /var/lib/apt/lists/*

      - name: Install dependency R packages
        run: |
          R -e "install.packages(c('XML','png','jpeg','base64enc','V8','plyr'))"

      - name: Install required R packages
        run: |
          R -e "devtools::install_github(\"sjp/grImport2\")"
          R -e "devtools::install_github(\"sjp/grConvert\")"

      - name: Rebuild images
        run: |
          R -e 'devtools::load_all(); generate_package_data(); message("Completed build");'

      - name: AddBuiltSugars
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automated sugars build
          commit_user_name: ggsugar actions bot
          file_pattern: R/*.rda data/*.rda
